CREATE
USER 'DBA_OMS'@'localhost' IDENTIFIED BY 'DBA_OMS_PASSWORD';
CREATE
USER 'DBA_OMS'@'%' IDENTIFIED BY 'DBA_OMS_PASSWORD';

GRANT ALL PRIVILEGES ON *.* TO
'DBA_OMS'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO
'DBA_OMS'@'%' WITH GRANT OPTION;

CREATE ROLE IF NOT EXISTS 'SAMPLE_RO'@'localhost';
CREATE ROLE IF NOT EXISTS 'SAMPLE_RO'@'%';

GRANT
SELECT
ON *.* TO 'SAMPLE_RO'@'localhost';
GRANT
SELECT
ON *.* TO 'SAMPLE_RO'@'%';

FLUSH
PRIVILEGES;
